// <auto-generated>
// Generated from contracts/workerHub.contract.json.
// Run: node tools/generate-worker-hub-contracts.mjs
// </auto-generated>

namespace FirstDraft.Api.Contracts
{
    internal static class WorkerHubContract
    {
        public const string HubPath = "/WorkerHub";

        public static class ServerMethods
        {
            public const string Handshake = "Handshake";
            public const string Register = "Register";
            public const string ExecuteCommandResult = "ExecuteCommandResult";
            public const string CommandOutputChunk = "CommandOutputChunk";
            public const string RefreshCommandToken = "RefreshCommandToken";
            public const string RejectCommand = "RejectCommand";
        }

        public static class ClientMethods
        {
            public const string ExecuteCommand = "ExecuteCommand";
        }

        public static class RegisterArguments
        {
            public const int AccessToken = 0;
            public const int ConnectionId = 1;
            public const int WorkerId = 2;
            public const int Paths = 3;
            public const int Skills = 4;
            public const int MaxConcurrentTasks = 5;
            public const int EnabledTaskTypes = 6;
            public const int GitRepositories = 7;
            public const int JiraIntegrations = 8;
        }

        public static class CommandOutputChunkArguments
        {
            public const int AccessToken = 0;
            public const int TransactionId = 1;
            public const int Sequence = 2;
            public const int Stream = 3;
            public const int Text = 4;
            public const int EmittedAt = 5;
        }

        public static class CommandResultArguments
        {
            public const int AccessToken = 0;
            public const int TransactionId = 1;
            public const int Result = 2;
            public const int ErrorMessage = 3;
        }

        public static class RefreshCommandTokenArguments
        {
            public const int AccessToken = 0;
            public const int TransactionId = 1;
        }

        public static class RejectCommandArguments
        {
            public const int AccessToken = 0;
            public const int TransactionId = 1;
            public const int Reason = 2;
        }

    }
}
