// <auto-generated>
// Generated from contracts/workerHub.contract.json.
// Run: node tools/generate-worker-hub-contracts.mjs
// </auto-generated>

export const workerHubPath = "/WorkerHub" as const;

export const workerHubServerMethods = {
  handshake: "Handshake",
  register: "Register",
  executeCommandResult: "ExecuteCommandResult",
  commandOutputChunk: "CommandOutputChunk",
  refreshCommandToken: "RefreshCommandToken",
  rejectCommand: "RejectCommand",
} as const;

export const workerHubClientMethods = {
  executeCommand: "ExecuteCommand",
} as const;

export const workerHubRegisterArguments = {
  accessToken: 0,
  connectionId: 1,
  workerId: 2,
  paths: 3,
  skills: 4,
  maxConcurrentTasks: 5,
  enabledTaskTypes: 6,
  gitRepositories: 7,
  jiraIntegrations: 8,
} as const;

export const workerHubCommandOutputChunkArguments = {
  accessToken: 0,
  transactionId: 1,
  sequence: 2,
  stream: 3,
  text: 4,
  emittedAt: 5,
} as const;

export const workerHubCommandResultArguments = {
  accessToken: 0,
  transactionId: 1,
  result: 2,
  errorMessage: 3,
} as const;

export const workerHubRefreshCommandTokenArguments = {
  accessToken: 0,
  transactionId: 1,
} as const;

export const workerHubRejectCommandArguments = {
  accessToken: 0,
  transactionId: 1,
  reason: 2,
} as const;
